apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- configuration.yaml

resources:
- webhook-cert.yaml
- manifests.yaml

commonAnnotations:
  cert-manager.io/inject-ca-from: kube-system/fastly-operator-webhook

patches:
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
  patch: |
    - op: replace
      path: /metadata/name
      value: fastly-operator
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: fastly-operator-admission
    - op: replace
      path: /webhooks/0/clientConfig/service/namespace
      value: kube-system
    - op: replace
      path: /webhooks/0/clientConfig/service/port
      value: 443
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
  patch: |
    - op: replace
      path: /metadata/name
      value: fastly-operator
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: fastly-operator-admission
    - op: replace
      path: /webhooks/0/clientConfig/service/namespace
      value: kube-system
    - op: replace
      path: /webhooks/0/clientConfig/service/port
      value: 443 