apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- operator.yaml
- service.yaml
- fastly-secret.yaml
- webhook/

images:
- name: fastly-tls-operator
  newName: fastly-tls-operator
  newTag: latest

commonAnnotations:
  app.kubernetes.io/name: fastly-tls-operator 