{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "fastly-operator.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "fastly-operator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.webhook.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fastly-operator.fullname" . }}-webhook
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fastly-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-platform-seatgeek-io-v1alpha1-fastlycertificatesync
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  name: vfastlycertificatesync-v1alpha1.platform.seatgeek.io
  rules:
  - apiGroups:
    - platform.seatgeek.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - fastlycertificatesyncs
  sideEffects: None
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 5 }}
{{- end }} 