# This rule is not used by the project fastly-tls-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.seatgeek.io.platform.seatgeek.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fastly-tls-operator
    app.kubernetes.io/managed-by: kustomize
  name: fastlycertificatesync-viewer-role
rules:
- apiGroups:
  - platform.seatgeek.io.platform.seatgeek.io
  resources:
  - fastlycertificatesyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.seatgeek.io.platform.seatgeek.io
  resources:
  - fastlycertificatesyncs/status
  verbs:
  - get
