//go:build !ignore_autogenerated

/*
Copyright 2025 SeatGeek.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastlyCertificateSync) DeepCopyInto(out *FastlyCertificateSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastlyCertificateSync.
func (in *FastlyCertificateSync) DeepCopy() *FastlyCertificateSync {
	if in == nil {
		return nil
	}
	out := new(FastlyCertificateSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FastlyCertificateSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastlyCertificateSyncList) DeepCopyInto(out *FastlyCertificateSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FastlyCertificateSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastlyCertificateSyncList.
func (in *FastlyCertificateSyncList) DeepCopy() *FastlyCertificateSyncList {
	if in == nil {
		return nil
	}
	out := new(FastlyCertificateSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FastlyCertificateSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastlyCertificateSyncSpec) DeepCopyInto(out *FastlyCertificateSyncSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastlyCertificateSyncSpec.
func (in *FastlyCertificateSyncSpec) DeepCopy() *FastlyCertificateSyncSpec {
	if in == nil {
		return nil
	}
	out := new(FastlyCertificateSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastlyCertificateSyncStatus) DeepCopyInto(out *FastlyCertificateSyncStatus) {
	*out = *in
	in.SubjectStatus.DeepCopyInto(&out.SubjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastlyCertificateSyncStatus.
func (in *FastlyCertificateSyncStatus) DeepCopy() *FastlyCertificateSyncStatus {
	if in == nil {
		return nil
	}
	out := new(FastlyCertificateSyncStatus)
	in.DeepCopyInto(out)
	return out
}
